name: signalbyt
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.7.0
  firebase_core: ^3.15.2
  cloud_firestore: ^5.6.12
  firebase_storage: ^12.4.10
  firebase_messaging: ^15.2.10
  #  firebase_crashlytics: ^3.0.6
  flutter_local_notifications: ^18.0.1
  provider: ^6.0.2
#  path_provider: ^2.0.2
  hive: ^2.0.4
  get: ^4.6.5
  dio: ^5.2.0
  flutter_spinkit: ^5.1.0
  modal_bottom_sheet: ^2.0.1
  google_sign_in: ^7.1.1
  sign_in_with_apple: ^7.0.1
  package_info_plus: ^8.3.1
#  flutter_animated_dialog: ^2.0.1

  flutter_styled_toast: ^2.1.3
#  url_launcher: ^6.1.10
#  url_launcher: ^6.1.4
  shimmer: ^3.0.0
  configurable_expansion_tile_null_safety: ^3.1.1
  json_annotation: ^4.0.0
  flutter_icons:
    git:
      url: https://github.com/adarsh-technocrat/flutter-icons.git
      branch: null-safety-migration
  share_plus: ^11.0.0
#  purchases_flutter: ^6.2.0
  image_picker: ^1.0.0
  cached_network_image: ^3.2.0
  #  image_cropper: ^5.0.0
  flutter_image_compress: ^2.0.3
  flutter_native_splash: ^2.2.16
  easy_localization: ^3.0.1
  flutter_dotenv: ^5.0.2
  flutter_widget_from_html_core: ^0.17.0
  #  fwfh_webview: ^0.14.2
  #  webview_flutter: ^4.0.5
  flutter_svg: ^2.0.2
  #  google_fonts: ^6.1.0
  socket_io_client: ^3.1.2
  custom_navigation_bar: ^0.8.2
  carousel_slider: ^5.1.1
  multiavatar: ^0.1.5
  #  google_mobile_ads: ^4.0.0
  get_storage: ^2.1.1
#  flutterwave_standard: ^1.0.7
  flutterwave_standard: ^1.1.0
  win32: ^5.2.0
  cupertino_icons: ^1.0.8
  percent_indicator: ^4.2.4
  font_awesome_flutter: ^10.8.0
  rive: ^0.13.4
  intl: ^0.20.2
  rxdart: ^0.27.7
#  crypto_market: ^0.0.3
  #  flutter_paypal: ^0.0.7
  flutter_animate: ^4.5.2
  #  firebase_core_web: ^2.11.5
  #  inapp_flutter_kyc: ^1.1.5
  #  idenfy_sdk_flutter: ^2.6.1
  #  win32: ^5.5.4
#  flutterwave: ^1.0.3
  fluttertoast: ^8.0.8
#  package_info: ^2.0.2
  shared_preferences: ^2.2.3
#  http: ^0.13.6
  http: ^1.3.0
  google_fonts: ^4.0.4
  flutter_bloc: ^9.1.1
  fl_chart: ^0.65.0
  url_launcher: ^6.3.2
  pay: ^3.2.1
  flutter_icons_null_safety: ^1.1.0
  purchases_flutter: ^9.10.8
  firebase_crashlytics: ^4.3.10
  webview_flutter: ^4.13.1
  fwfh_webview: ^0.15.6
  glassmorphism: ^3.0.0
  animate_do: ^4.2.0
  firebase_app_check: ^0.3.2+10
#  firebase_core_web: ^2.11.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.4
  build_runner: ^2.0.4
  #flutter packages pub run flutter_launcher_icons:main
  flutter_launcher_icons: ^0.14.4
flutter_icons:
  image_path: "assets/icon/icon.png"
  android: true
  remove_alpha_ios: true
  ios: true

flutter_native_splash:
  color: "#000000"
  image: assets/icon/splash_icon.png
  ios: true
  android: true

flutter_launcher_icons:
  android: "launcher"
  ios: true
  image_path: "assets/icon/icon.png" # Your icon (1024x1024 recommended)

flutter:
  uses-material-design: true

  fonts:
    - family: gainers
      fonts:
        - asset: assets/icon/ic_gainers.ttf
    - family: message
      fonts:
        - asset: assets/icon/ic_message.ttf
    - family: tab
      fonts:
        - asset: assets/icon/ic_tab.ttf
    - family: wallet
      fonts:
        - asset: assets/icon/ic_wallet.ttf
    - family: tab1
      fonts:
        - asset: assets/icon/ic_tab1.ttf
    - family: tab2
      fonts:
        - asset: assets/icon/ic_tab2.ttf
    - family: tab3
      fonts:
        - asset: assets/icon/ic_tab3.ttf
    - family: tab4
      fonts:
        - asset: assets/icon/ic_tab4.ttf
    - family: tab5
      fonts:
        - asset: assets/icon/ic_tab5.ttf
    - family: loser
      fonts:
        - asset: assets/icon/ic_loser.ttf
    - family: Sans
      fonts:
        - asset: assets/font/OpenSans-Bold.ttf
          weight: 800
        - asset: assets/font/OpenSans-Semibold.ttf
          weight: 600
        - asset: assets/font/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/font/OpenSans-Light.ttf
          weight: 200
    - family : Popins
      fonts:
        - asset: assets/font/Poppins-Regular.ttf
          weight: 400
        - asset: assets/font/Poppins-SemiBold.ttf
          weight : 600
    - family : Berlin
      fonts:
        - asset: assets/font/BRLNSDB.TTF
          weight: 700
    - family : Lemon
      fonts:
        - asset: assets/font/Lemon-Regular.ttf
          weight: 400
    - family : Gotik
      fonts:
        - asset: assets/font/GOTHIC.TTF
          weight: 400
        - asset: assets/font/GOTHICB.TTF
          weight : 600
    - family : Pragmatica
      fonts:
        - asset: assets/font/pragmatica_bold.ttf
          weight: 500


  assets:
    - .env
    - assets/images/
    - assets/pairs/
    - assets/svg/
    - assets/icon/
    - assets/translations/
    - assets/samples/animations/
    - assets/samples/ui/rive_app/
    - assets/samples/ui/rive_app/rive/
    - assets/samples/ui/rive_app/images/
    - assets/samples/ui/rive_app/images/backgrounds/
    - assets/samples/ui/rive_app/images/topics/
    - assets/samples/ui/rive_app/images/avatars/
    - assets/image/splash_screen.png
    - assets/image/loginHeader.png
    - assets/image/logo.png
    - assets/image/user.png
    - assets/image/signupHeader.png
    - assets/image/gainers.png
    - assets/image/losers.png
    - assets/image/article1.jpg
    - assets/image/create_wallet.png
    - assets/image/setting/lightMode.png
    - assets/image/setting/nightMode.png
    - assets/image/qrCode.png
    - assets/image/messageAppbar.png
    - assets/image/T1_noMessage.png
    - assets/images/logo.png
    - assets/images/uniswap.png
    - assets/images/pancakeswap.png
    - assets/images/binance.png

